### ISSUE TITLE
devops: create guide for deploying the service on lightsail or similar VPS service 

### ISSUE THREAD

**Issue by tfolbrecht** [devflowinc/trieve#1102]
### Description

Make an easy way to get started with Trieve 

### Target(s)

Ops

### Requirement to close

A `docker-compose.yml` file that deploys a local version of the app and shows off core functionality

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by tfolbrecht** [comment]
* [X] keycloak (baked configs from keycloak dir
* [X] server-no-ocr 
* [X] server-ocr
* [X] ingest
* [ ] splade-embeddings (prebake huggingface models OR download with user's hugging face api key)
* [ ] search (runtime configuration)
* [ ] chat (runtime configuration)

**Comment by skeptrunedev** [comment]
Punting this back to `No Status` as we really need to move forward w/ Sentry

**Comment by skeptrunedev** [comment]
Blocked by trying to get keycloak to connect by default

**Comment by cdxker** [comment]
Just commented to mention issue is made for what this is blocked by https://github.com/devflowinc/trieve/issues/1474
