### ISSUE TITLE
observability: make error messages more clear

### ISSUE THREAD

**Issue by fastfists** [devflowinc/trieve#1129]
### Description

- [x] #1213
- [ ] #1218

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Dup of #1218
