### ISSUE TITLE
feature: replace redis queue implementation with Kafka or other MQ

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1136]
### Description

The current MQ system is a redis queue which is not a great solution. The goal is to migrate to something more robust. 

The first step here should be researching and picking a MQ system to use. I think Kafka should start in the #1 position and we should go from there. 

### Target(s)

`server`, `ingestion-microservice`

### Requirement to close

Merged PR that swaps from Redis queue to something more robust. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Closing for now. The draft PR for this is very good, but due to existing customer deployments and burden of running more infra will delay a migration.
