### ISSUE TITLE
ops: autogenerate sdk's with a CI action when the openapi spec changes

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1137]
### Description

This CI action should attempt to create a PR to https://github.com/devflowinc/trieve-ruby-client everytime the openapi spec changes. Should be flexible to also work with python, and typescript clients once they get generated.

To generate the openapi spec run 
```
cargo run --bin redoc_ci > openapi.json
```

Helpful links
- https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action <- Using gh cli
- https://github.com/marketplace/actions/create-pull-request <- GH marketplace PR action

### Target(s)

`ops`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by tfolbrecht** [comment]
@fastfists How do you want this to work?

Do you want to trigger the downstream trieve-ruby-client build job after new PR's hit main from the trieve repo?

**Comment by cdxker** [comment]
Closing this issue, autogen pull requests is a little bit too ambitious at the moment. 
We will be able to survive if we switch to this instead #1476
