### ISSUE TITLE
documentation: explain on docs page and in openapi spec that we translate ISO8601 time to Unix Epoch for numeric filter

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1165]
### Description

Right now it's confusing that you send an ISO8601 time stamp to the api and then search time filters using numeric. Need to explain how this works better. 

### Target(s)

`server`,`documentation`

### Requirement to close

PR to `trieve` that updates the openapi spec to explain how this works. 

**Wish-list item**: PR to `documentation` with a note on how to do this there as well. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by densumesh** [comment]
Should prob just parse filters coming in for timestamp into Unix timestamp from iso string
