### ISSUE TITLE
bugfix: `group_tracking_ids` currently do not work because Qdrant does not have them 

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1167]
### Description

![image](https://github.com/devflowinc/trieve/assets/15804464/aac7f007-4c06-4c8a-a1f7-c67dd8183bc3)

When users send a filter with `group_tracking_ids`, we need to translate it into a `group_ids` filter. 

### Target(s)

`server`

### Requirement to close

PR that makes filtering with `group_tracking_ids` work. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by fastfists** [comment]
We could fetch the group_id from group_tracking_id

**Comment by skeptrunedev** [comment]
> We could fetch the group_id from group_tracking_id

That's the plan, yeah
