### ISSUE TITLE
feature: also return `group_tracking_id` everywhere that we return `group_id`

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1169]
### Description

For proejcts that integrate using `group_tracking_id`, we need to return the `group_tracking_id` so that they are able to coordinate with their systems. 

### Target(s)

`server`

### Requirement to close

Merged PR which results in `group_tracking_id` being returned for at least the `group_search` and `group_recommendation` routes. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by fastfists** [comment]
What if no group_tracking_id exists? This is very likely going to break our frontends also.
