### ISSUE TITLE
feature: add loading indicator to events tab on dashboard

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1171]
### Description

When viewing the events tab in dashboard, it can take a bit to load in and can make something feel like there is an error. 

### Target(s)

`dashboard`

### Requirement to close

PR that adds loading indicator to events tab on dataset view in `dashboard`.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by Aryakoste** [comment]
Hello. @skeptrunedev. I would like to work on this issue.

**Comment by skeptrunedev** [comment]
> Hello. @skeptrunedev. I would like to work on this issue.

Have at it! Assigned 🍻

**Comment by Aryakoste** [comment]
I am getting CORS error whenever i try to hit the API where can i setup the CORS url.
