### ISSUE TITLE
feature: use Postgres to filter when a user tries to filter by a metadata field

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1198]
### Description

Qdrant does not index the metadata field so it is very slow to filter by it. Whenever a user provides a `metadata.key` value into the filter, we should instead do a pg filter and then pass a `HasId` filter to qdrant to be more performant and scalable.

### Target(s)

`server`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
This is very smart
