### ISSUE TITLE
feature: add toasts for all errors

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1265]
### Description

We don't handle alot of error states so just put the response text in a toast on the frontend if an error occurs.

### Target(s)

`search`, `chat`, `dashboard`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by Aryakoste** [comment]
Hello @densumesh @fastfists. I would like to work on this issue.

**Comment by densumesh** [comment]
Sounds good I'll assign you the issue @Aryakoste!
