### ISSUE TITLE
feature: add ability to be able to go directly to the search page for a dataset

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1314]
### Description

Currently, you have to manually navigate to the dataset you want to search from the dashboard. You should be able to have a button to take you to the search page for that specific dataset using the dataset-id url param for the search client

### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Also add `dashboard` link in `search` and `chat`
