### ISSUE TITLE
feature: show active invites with accepted status on admin-dashboard

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1344]
### Description

It is confusing to invite a user then not see whether or not they have accepted. We should fix this. 

### Target(s)

`server`

### Requirement to close

PR that adds invite status to admin dash. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by rohit-garga** [comment]
Hi @skeptrunedev I would like to work on this issue
