### ISSUE TITLE
bugfix: instead of displaying old data when switching orgs, put a loading indicator

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1361]
### Description

Currently when switching orgs, the data from the previous org remains. We should add a loading indicator or a animate pulse skeleton UI so that users know that the new org data is being loaded.

### Target(s)

`dashboard`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by drew-harris** [comment]
Could not recreate / interface was definitely fast enough
