### ISSUE TITLE
feature: allow users to update cards they have created

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#140]
Blocked by #138 

- [x] card update route
- [x] update route takes both card_content and card_html
- [x] update route takes `private` flag
- [x] update route handles updating of content & cardHtml
- [x] update vector in qdrant on content update
- [x] db migration for soft-deleting votes
- [x] if updating card from `private==false` to `private==true` and `qdrant_point_id` is not `None`, set the private metadata field on its Qdrant record to true
- [x] if updating card from `private==false` to `private==true` and `qdrant_point_id` is not `None`, soft delete all votes for the card
- [x] if updating from `private==true` to `private==false`, dup check and create Qdrant record
- [x] if updating from `private==true` to `private==false`, restore all votes that were soft-deleted

**Comment by densumesh** [comment]
"if updating card from private==false to private==true and qdrant_point_id is not None, delete Qdrant record"  why are we deleting the qdrant_point_id? We just need to set the private flag to true and then qdrant won't return it.
