### ISSUE TITLE
feature: store docx and html files in cloud on user upload

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#142]
- [x] pick some S3 alternative that is cheap to store the files
- [x] db migration for table that holds files (uuid, user_id, file_name, private, created_at, updated_at)
- [x] #159
- [x] #161
- [x] #167
- [x] #165 
- [x] #168 
- [x] #163
- [x] modify upload route to have a `private` flag

**Comment by densumesh** [comment]
taking on https://github.com/arguflow/ai-editor/issues/159
