### ISSUE TITLE
ops: better sdk management

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1476]
### Description

- [ ] Move SDK's to monorepo under `sdk/<lang>`
- [ ] CI action similar to https://github.com/devflowinc/actix-web-starter/pull/18 to check that sdk is correctly updated for each language.
- [ ] Script in `scripts/` directory to regenerate the code docs that is expected to be ran locally
- [ ] CI action to auto deploy / publish sdk's if modification occurs

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
At the moment this is out of scope. In the future, we will revisit and clean up code for better client libs.
