### ISSUE TITLE
bugfix: issue with ingestion worker spiking CPU usage

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1505]
### Description

In Kube we see the ingestion worker spike CPU usage to 100%. This needs to be fixed. 

### Target(s)

`ingestion-worker`

### Requirement to close

PR which lowers CPU usage for ingestion worker in Kube. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by jooni22** [comment]
if you have 1 core/cpu in Kube, where ingestion-worker is running, it will probably consume all the resources, while with multiple cores, it uses only one, same as file-worker.
![image](https://github.com/devflowinc/trieve/assets/20043534/1754a611-4bc6-4f4e-909f-b6863b84c44a)
