### ISSUE TITLE
bugfix: Metadata on search shows [object Object]

### ISSUE THREAD

**Issue by akhileshsharma99** [devflowinc/trieve#1535]
### Description

If an object is uploaded to metadata then the search on the frontend shows [object Object]

<img width="400" alt="Screenshot 2024-06-01 at 8 42 35 PM" src="https://github.com/devflowinc/trieve/assets/72787785/bc352d63-5449-4e4b-a6cf-4e32ab1ee22d">

### Target(s)

Search

### Requirement to close

don't show [object Object]

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
The path to the component that needs to be modified - `search/src/components/ScoreChunk.tsx`
