### ISSUE TITLE
docs: create local development guide

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1545]
### Description

Create guide on how to run locally for developers wanting to use trieve to test without relying on the API alone.

### Target(s)

`docs`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by densumesh** [comment]
blocked by #1534

**Comment by cdxker** [comment]
Closing this issue, its just too much for now. Will think about revisited after better docker-compose / kubernetes setup is completed.
