### ISSUE TITLE
bugfix: support for redis-clusters in the ingestion and file-worker

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1546]
### Description

The command `brpoplpush ingestion processing 1.0`  causes an error when redis is in cluster mode
```sh
redis.cache.net:6380> brpoplpush ingestion processing 1.0
(error) CROSSSLOT Keys in request don't hash to the same slot
```

Need to add HashTags to this command to prevent this error.
https://stackoverflow.com/questions/38042629/redis-cross-slot-error 

### Target(s)

`file_worker` `ingestion_worker`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
The real issue here was the multi-threading and not redis-pool, so this is unplanned for now.
