### ISSUE TITLE
docs: guide for local development of kubernetes

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1554]
### Description

Research best tool for local kube
- `minikube`
- `kind`
- `k3d`
- `k3s`
- `rancher`
- `microk8s`

`kind` seems to be the best.
Aside from that just a quick setup, and ensure that GPU embedding can work.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by cdxker** [comment]
re

**Comment by cdxker** [comment]
The only thing that is blocking this from working properly is keycloak being stubborn about ssl. Might need to block out some time to get this working within kubernetes.

It is blocking us from maintaining a proper `helm` chart since there is no way to test yaml files locally without deploying it to production.

**Comment by skeptrunedev** [comment]
> The only thing that is blocking this from working properly is keycloak being stubborn about ssl. Might need to block out some time to get this working within kubernetes.
> 
> It is blocking us from maintaining a proper `helm` chart since there is no way to test yaml files locally without deploying it to production.

Does setting `KC_PROXY` to `edge` help?

**Comment by cdxker** [comment]
Found something very useful that came out in June https://github.com/keycloak/keycloak/releases/tag/25.0.0

**Comment by cdxker** [comment]
https://github.com/ramosbugs/openidconnect-rs/issues/75#issuecomment-1167924180
