### ISSUE TITLE
Feature: ollama for embeddings 

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#1563]
### Description
Right now the ollama embeddings don't support OpenAI format. 
https://github.com/amikos-tech/ollama/pull/1
https://github.com/amikos-tech/ollama/pull/2
Someone uploaded a pull request with an implementation of the OpenAI format, but it was not included in the main branch.

### Target(s)

 `server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
The solution here would be to use https://github.com/BerriAI/litellm as a proxy. 

This isn't something we intend to put into the Trieve main repo, so I will close for now.
