### ISSUE TITLE
feature: include `api-version` in the `EMBEDDING_SERVER` env values

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#1567]
### Description

![image](https://github.com/devflowinc/trieve/assets/20043534/06ddac0c-8dea-4290-a20e-1c2610b836c0)
https://github.com/search?q=repo%3Adevflowinc%2Ftrieve%202023-05-15&type=code

### Target(s)

`server`, `search`, `chat`

### Requirement to close

One example how it can be fixed
![image](https://github.com/devflowinc/trieve/assets/20043534/025314b3-ab6f-4b3b-84ec-6aa1e4081510)

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by cdxker** [comment]
The issue with this is that the `EMBEDDING_SERVER_ORIGIN` should just be "http://192.1681.146:8000". The server internally adds `/embeddings`. the `api-version` section is just used to be compatible with azure openai.

**Comment by jooni22** [comment]
that's what depends on what direction you want to go, if trieve is to support as many possible implementations of model providers for embeddings/reranking/sparse as possible, it needs to be improved because the current code doesn't allow for anything other than embeddings.trieve.ai and azure openai. A direction needs to be taken to solve this problem. I have 2 suggestions:
1. all checked API providers are listed one by one in .env for example:
EMBEDDING_SERVER_ORIGIN_AZURE=xx.xx.xx.xx.xx
EMBEDDING_SERVER_ORIGIN_OPENAI=xx.xx.xx.xx.xx
EMBEDDING_SERVER_ORIGIN_OLLAMA=xx.xx.xx.xx.xx
EMBEDDING_SERVER_ORIGIN_CUSTOM=xx.xx.xx.xx.xx
2. there is one variable left, which can be voluntarily assigned
EMBEDDING_SERVER_ORIGIN=xx.xx.xx.xx.xx/v1/....
The current way is weak in my opinion, because during implementation you constantly have to look into the code and tweak and re-build it, which sometimes can be problematic or simply too long. I myself currently have it this way and find it convenient.
SPARSE_SERVER_QUERY_ORIGIN="http://192.168.1.146:9202/embed_sparse"
SPARSE_SERVER_DOC_ORIGIN="http://192.168.1.146:9201/embed_sparse"
EMBEDDING_SERVER_ORIGIN="http://192.168.1.146:8000/embeddings"
EMBEDDING_SERVER_ORIGIN_BGEM3="http://192.168.1.146:8000/embeddings"
RERANKER_SERVER_ORIGIN="http://192.168.1.146:9203/rerank"
