### ISSUE TITLE
GitHub Stars

### ISSUE THREAD

**Issue by JuanPabloDiaz** [devflowinc/trieve#1568]
### Description

Consider changing the display of star ratings to '1K' once the count reaches 1,000.

![image](https://github.com/devflowinc/trieve/assets/25883220/3f124469-a127-4e22-a6f6-b61238c12d90)

**Comment by skeptrunedev** [comment]
I actually tend to like having the exact count. Is there a specific reason why you'd prefer `1K`?

**Comment by JuanPabloDiaz** [comment]
Easy to read and it's probably the common way to display it.

It is just a suggestion. 🙂

**Comment by skeptrunedev** [comment]
Hey, going to close this for now. Will think about changing it in the future though!!
