### ISSUE TITLE
feature: `clear dataset` API route and button for dashboard

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1622]
### Description

While there is currently a way to delete a dataset and create a new one, there also be a way to empty a dataset without deleting it. 

### Target(s)

`dashboard`,`server`

### Requirement to close

PR which adds the ability to clear dataset instead of just deleting it. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by drew-harris** [comment]
Waiting on  #1621 to merge because those changes will come in very handy
