### ISSUE TITLE
feature: update group chunks trigger

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1634]
### Description

There should be a way to trigger a batch update of a group's chunks such that they inherit some values held on the group level. I.e. tags, num_value, metadata. 

### Target(s)

`server`

### Requirement to close

PR which adds a way to trigger updates on chunk's to match their group. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by aaryanpunia** [comment]
##### V1
- New route that batch updates the `tagset` of grouped chunks
	- Will pass a message to `group_worker` to accomplish this.
- New `group_worker` that handles batch updates to grouped chunks
	- Poll a queue in redis and perform batch operations on chunks in groups.
- New redis queue that contains messages related to batch operations on grouped chunks.
- New operator that updates the tagset of grouped chunks 1000 at a time
	- This operator will take the tags not present a chunk's `tagset` but in a group's `tagset` and add that to the chunk's `tagset`
- New operator that passes messages to `group_worker`
- New message type `struct GroupUpdateTagset`
