### ISSUE TITLE
cleanup: change response format for `ScoreChunk` such that it's easier to comprehend

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1669]
### Description

The really hard part of this is that it has to be done without changing response format for existing users. 

I think the way to do this is opt in with `ServerDatasetConfiguration`. 

![image](https://github.com/devflowinc/trieve/assets/15804464/49c6801f-fc52-4197-9fbe-3e64a42da321)

### Target(s)

`server`,`search`,`dashboard`

### Requirement to close

PR which changes response type for `ScoreChunk`. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by densumesh** [comment]
Blocked by API versioning logic
