### ISSUE TITLE
feature: support SSO authentication with keycloak

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1697]
### Description

SSO is a big security win for those who have it and use the cloud version. It should be supported. 

What needs modification is the realm-export.json file for keycloak. The SSO support should all be internal to keycloak and not related to the actual Rust server.

### Target(s)

`server`

### Requirement to close

PR to add SSO into the Keycloak config which loads when the docker image starts. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by abhishek818** [comment]
@skeptrunedev can I get this assigned?

**Comment by varshith257** [comment]
I have a similiar experience with keycloak and putting my attempt for this issue
/attempt #1697

**Comment by skeptrunedev** [comment]
> @skeptrunedev can I get this assigned? Since this is a big enough feature..

We don't assign issues, but the first PR to fulfill the requirements to close will get the bounty!

**Comment by varshith257** [comment]
@skeptrunedev Tracking here, I will update with fixing docker errors araised

**Comment by skeptrunedev** [comment]
Will come back to this at a later date when we have more time to scope it out.

**Comment by varshith257** [comment]
@skeptrunedev I agree for it. Any tip for the till now efforts taken will be greatly appreciated :)
