### ISSUE TITLE
feature: remove collisions

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1699]
### Description

Need to remove ALL references to collisions including in the frontends. Should remove `ScoreChunkArray` componenets on fronted. Make the `qdrant_point_id` not optional in DB and drop the `ChunkCollisions` table. Modify the ingestion microservice as well.

### Target(s)

`server`, `search`, `chat`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Completed in #1757
