### ISSUE TITLE
docs: replace date_recency with recency_bias on the search example

### ISSUE THREAD

**Issue by llermaly** [devflowinc/trieve#1726]
### Description

On the documentation: https://docs.trieve.ai/api-reference/chunk/search

The example shows `date_bias:true` , and `recency_bias` is not set, but then `recency_bias` is explained below, but date_bias it is not. 

Only `recency_bias` is accurate.
### Target(s)

`server`

### Requirement to close

Documentation showing `recency_bias` instead of `date_bias` on the example.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Edited the issue to make the target `server` as that is where the docstrings for the OpenAPI spec are.

**Comment by densumesh** [comment]
fixed by #1725
