### ISSUE TITLE
feature: indicate datasets loading while requests are being made on dashboard such that users know why search may not be finding their dataset

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1745]
### Description

![image](https://github.com/devflowinc/trieve/assets/15804464/ab5741cd-6603-4a33-bdbc-bcab90d59f04)

Search queries should also be retried as datasets are loading. 

### Target(s)

`dashboard`

### Requirement to close

PR which adds the features specified in the image and text of the description. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by rajeshj11** [comment]
\attempt #1745
