### ISSUE TITLE
feature: add buttons to dataset overview in dashboard to open search and RAG playgrounds

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1750]
### Description

![image](https://github.com/devflowinc/trieve/assets/15804464/f20e51d9-dd66-4759-90e0-4422917505a9)

Both buttons should open the link in a tab with the proper URL query params such that the correct dataset is selected on the UI's. 

### Target(s)

`dashboard`

### Requirement to close

PR which adds buttons to the dashboard Dataset overview page. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by varshith257** [comment]
@skeptrunedev Can you assign me this issue?
