### ISSUE TITLE
bugfix: after selecting a group, it returns to the first dataset

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#1751]
### Description

After selecting a group, it returns to the first dataset. More in GIF

![output](https://github.com/devflowinc/trieve/assets/20043534/f5dbcfbe-5a07-49e6-af5f-ce1f2f0cbaa2)

### Target(s)

`search`

### Requirement to close

PR which fixes the bug. The PR should include a screen recording showing that the issue is fixed. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by varshith257** [comment]
/attempt #1751

@skeptrunedev Is assignment of an issue is required? or Can raise PR directly with a fix?
