### ISSUE TITLE
feature: api versioning

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1753]
### Description

We want to be able to version the API so that we can push breaking changes to users in a safe way. This should be accomplished by adding a new `X-API-Version` header that can be set to 1 or 2. We should also switch users onto the new api version if they create a new organization after this PR gets merged.

This PR should just create the underlying code to add the header and versioning logic, as well as update the clients to use the new version.

We need to then complete this issue:
- [ ] #1669

### Target(s)

`server`, `chat`, `search`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
If unspecified, orgs created before a certain date should default to version 1 and orgs after a certain date should default to 2.
