### ISSUE TITLE
bugfix: search and RAG playground orgs should be set to whatever org user was previously on

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#1766]
### Description

To replicate:

Select a given org and click Search Playground and RAG Playground

Notice how it will stick to a seemingly random org and dataset.

Let's fix it so that the playgrounds always open set to the org the user was previously on.

If I was configuring the X org, I want the Search and RAG Playgrounds to open with the X org, not a random org like Y or Z.
### Target(s)

search, chat

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Finished in #1782
