### ISSUE TITLE
bug: let's fix this the storage number 

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#1791]
### Description

This number doesn't make sense. I love our big quirky number but we should make sure that it reflects the tier of the user.

![Screenshot 2024-07-05 at 10 36 46 AM](https://github.com/devflowinc/trieve/assets/111924063/2432cd77-634e-4cdc-88d3-dafcffa163c6)

### Target(s)

'dashboard'

### Requirement to close

Let's make sure this displays an appropriate number for storage.
 
### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
This won't require any changes to the code. It's an issue with the setting on the PRO plan. Will modify

**Comment by skeptrunedev** [comment]
Fixed in #1783
