### ISSUE TITLE
bugfix: in a assistant completion message, when square brackets are generated in the response, MD render does not work properly

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#1810]
### Description

![image](https://github.com/devflowinc/trieve/assets/20043534/aaffa908-90e9-4888-b591-e7a83d2987ce)
When square brackets are generated in the response, the Markdown render does not work properly, and render raw HTML tags.

### Target(s)
The issue affects the "chat" feature.
### Requirement to close
Fix
### Code snippet:
The image show a jq command that processes JSON data. It checks for specific conditions related to the "type" field and constructs HTML button elements with onclick events.
### Problem visualization:
On the image highlights parts of the code in red, showing where HTML tags like <span> and <button> are being generated within the jq command output.
### Expected behavior:
It seems the Markdown renderer should be processing these tags, but instead, they are appearing as raw text in the chat interface.

This issue appears to be related to how the chat interface handles Markdown rendering when the response contains dynamically generated HTML elements, particularly those with square brackets. The problem likely stems from conflicts between Markdown parsing and the insertion of raw HTML tags in the output.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by aaryanpunia** [comment]
Hi! Can you provide a sample input in text that would reproduce this issue?

**Comment by aaryanpunia** [comment]
can repro by setting system prompt to something like only return ` ```[0] ``` `
only happens with code elements

**Comment by skeptrunedev** [comment]
Let's just remove the replace logic - https://github.com/devflowinc/trieve/blob/main/frontends/chat/src/components/Atoms/AfMessage.tsx#L106-L115
