### ISSUE TITLE
BUG Select and copy text doesn't work in chat

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#1812]
### Description

Select and copy text doesn't work in chat
![image](https://github.com/devflowinc/trieve/assets/20043534/382207a4-f665-4f21-a3db-73409611b43d)
The text in red highlight, can't be copy, only possible to copy is the context from doc.
![copy](https://github.com/devflowinc/trieve/assets/20043534/42434ef2-f7a3-4943-a375-33f4c0f12571)

### Target(s)

Chat

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Can you include more details? A screenshot of problematic text or quick screen recording would be really great!

**Comment by jooni22** [comment]
> Can you include more details? A screenshot of problematic text or quick screen recording would be really great!

enough? :)

**Comment by skeptrunedev** [comment]
> > Can you include more details? A screenshot of problematic text or quick screen recording would be really great!
> 
> enough? :)

Absolutely! Thank you

**Comment by skeptrunedev** [comment]
Fixed!!
