### ISSUE TITLE
feature: add minimum score requirement for documents used in chat

### ISSUE THREAD

**Issue by vid277** [devflowinc/trieve#1817]
### Description
The documents referenced in a chat response are sometimes completely irrelevant. 

![image](https://github.com/devflowinc/trieve/assets/74870683/b7a6ff9b-0e94-4259-8518-cda966570435)

For example, given the query, "Who is Plato?" using the example YC companies dataset returns documents that are completely irrelevant to the generated chat response. 

We should add a minimum score requirement for the documents referenced in a response.  

### Target(s)
`server`, `chat`

### Requirement to close

PR to add a minimum score requirement for referenced documents in chat. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Finished in https://github.com/devflowinc/trieve/pull/1853
