### ISSUE TITLE
enhancement: dataset list also search by dataset id

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1818]
### Description

The dataset list should do a search on either dataset id or name.

### Target(s)

`dashboard`

### Requirement to close

![image](https://github.com/devflowinc/trieve/assets/32852291/b06ea60e-98ad-4936-9183-81a8589f45e6)

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
This functionality already existed and the issue was likely just that datasets were still loading in or this id actually was not present.
