### ISSUE TITLE
bugfix: it appears that one chunk in the assistant stream for `create_message` is coming back with empty metadata every time

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1834]
### Description

When using the RAG chat on our docs for Mintlify it seemed that one chunk in the results present on the stream was always missing its `metadata`. Something here seems wrong and should be fixed. It's likely an issue with hybrid of some kind. 

### Target(s)

`server`,`chat`

### Requirement to close

PR which both shows identification of the issue with testing reproduction and fixes it. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by aaryanpunia** [comment]
this is fixed, metadata just didn't exist for those chunks in the first place.
