### ISSUE TITLE
feature: add bm42 to huggingface/text-embeddings-inference

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1840]
### Description

Add support for `Qdrant/all_miniLM_L6_v2_with_attentions`

### Target(s)

https://github.com/huggingface/text-embeddings-inference

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by cdxker** [comment]
https://github.com/huggingface/text-embeddings-inference/pull/338

**Comment by skeptrunedev** [comment]
PR to add support for BM42 into TEI has been released - https://github.com/huggingface/text-embeddings-inference/pull/338
