### ISSUE TITLE
feature: add frontend cards for recommendation analytics

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1858]
### Description

Need to add frontend cards for these recommendation analytics.

![image](https://github.com/devflowinc/trieve/assets/25559111/101df5f1-f003-485f-b2ea-bb0e90bb824e)
### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Punting on this in liu of #2059
