### ISSUE TITLE
enhancement: reindex route for BM25

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1869]
### Description

Route to fully reindex a dataset. This can include changing the embedding models. This will remebed all vectors and reindex them into qdrant using a `reindex` worker.

### Target(s)

`server`

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
This needs to be respec'ed to minimize scope such that it only covers re-indexing logic for BM25

**Comment by skeptrunedev** [comment]
Closed in https://github.com/devflowinc/trieve/pull/1927
