### ISSUE TITLE
optimization: add opt-in feature flag to use gRPC with TEI

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#1872]
### Description

Because dense vectors are large gRPC can be a big advantage. It would be a nice latency optimization to use gRPC with TEI. It should be an opt in env such that users don't have their existing deployments broken. 

### Target(s)

`server`

### Requirement to close

PR which adds an opt-in env to use gRPC with TEI

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by jooni22** [comment]
It can only be a wrapper using:
https://github.com/fullstorydev/grpcurl
then the implementation would be fast, whereas I don't know if this would affect the additional latency.
As for the implementation in Rust code, I found such material, it might be useful:
https://dev.to/martinp/roll-your-own-auth-with-rust-and-protobuf-24ke
https://medium.com/@govinda.attal/rust-grpc-service-6f7188e49a3c
https://medium.com/@govinda.attal/rust-grpc-service-first-season-concludes-9b077421a303

**Comment by skeptrunedev** [comment]
After evaluating in https://github.com/devflowinc/trieve/pull/1936 we learned that there is no consistent latency benefit to using gRPC over REST. For this reason we do not plan to implement this. 

@jooni22 found the same result and shared in our Matrix community.
