### ISSUE TITLE
bugfix: reduce dashboard bundle size

### ISSUE THREAD

**Issue by drew-harris** [devflowinc/trieve#1873]
### Description

![image](https://github.com/devflowinc/trieve/assets/61394759/b4479cbc-efdb-4bb2-8da9-2220a5729f19)
After I upgraded Shiki to render the code examples, every single theme is being added to the Javascript bundle.

### Target(s)
`dashboard`

### Requirement to close

Remove the extra themes from the bundle.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by drew-harris** [comment]
Assuming that it is still code splitting properly, shouldn't reduce load times, therefore lower priority but worth looking for an easy fix.

**Comment by aaryanpunia** [comment]
done
