### ISSUE TITLE
feature: bm42 support

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1893]
### Description

- [ ] Ingest worker supports bm42
- [ ] BM42 Server
- [ ] Frontends Support BM42

### Target(s)

`server` `search` `dashboard`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Closing this as unplanned for now. Decided to go with BM25.
