### ISSUE TITLE
bugfix: Downloading groups file in search component doesn't  work

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#1913]
### Description

Downloading groups file in search component doesn't  work. When you press the "Download uploaded file" icon, it redirects to a file on AWS with a message:
```
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>.
```
![download_dataset](https://github.com/user-attachments/assets/191f8ae8-7477-4e65-bd84-0f5ff993b7be)

### Target(s)

search

**Comment by skeptrunedev** [comment]
cc @cdxker I think S3 is probably mis-configured. This is working locally

**Comment by cdxker** [comment]
This is working on production, when was this file uploaded? I know upload/download wasn't working with s3 for a while. It is possible the file wasn't uploaded correctly

**Comment by cdxker** [comment]
Closing as not reproducible.
