### ISSUE TITLE
bugfix: no redirection when changing dataset in file subview    

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#1914]
### Description

When changing the dataset in the file sub-glade, the redirection is missing. In my opinion, it should redirect to the selected dataset, to the list of groups

![switch](https://github.com/user-attachments/assets/74d51b1e-c7d9-46c2-a243-b26d430eb17b)

### Target(s)

search

**Comment by skeptrunedev** [comment]
Likely a simple fix to add something within an effect of the `GroupPage` that re-fetches the group and chunks in a group when the dataset changes.

**Comment by aaryanpunia** [comment]
can repro by setting system prompt to something like only return ``` ```[0] ``` ```
only happens with code elements
