### ISSUE TITLE
feature: add titles or labels to the three buttons (Settings, Delete, Clear) on the last column of the Datasets table in Dashboard > Overview

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve#1956]
### Description

The Settings, Delete, and Clear buttons in the far right column of the Datasets table on the Dashboard > Overview do not have titles or labels. Users may not be able to tell what the buttons do before clicking (especially the Clear button). (The buttons in the Tools column do have titles.)

Location: https://dashboard.trieve.ai

### Target(s)

dashboard

### Requirement to close

PR closed which wraps buttons into tooltip which specifies their purpose

**Comment by skeptrunedev** [comment]
Added a requirement to close. +1 from me for this being something to do. It's definitely confusing rn

**Comment by drew-harris** [comment]
I feel like the buttons should be moved into a dropdown menu ([like this one for example](https://ui.shadcn.com/docs/components/dropdown-menu)), or moved into the dataset page itself. Adding those controls page could be a good replacement for part of the "getting started" card
