### ISSUE TITLE
feature: add visual contrast or text to indicate that query instance rows are clickable in Low Confidence Queries and No Result Queries

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve#1959]
### Description

Currently the rows (individual query instances) in the "Low Confidence Queries" and "No Result Queries" tables in Search Analytics are clickable but the only indication of the affordance is the cursor changing to `pointer` on hover (the rows have a `cursor-pointer`class). 

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/7262d908-6307-483c-b1b8-c14b58dc0ce3">

This popup dialog will appear:
<img width="393" alt="image" src="https://github.com/user-attachments/assets/f782a67e-058a-4449-a26c-7b87337eddd5">

The head queries rows have the same visual appearance, but are not clickable (and do not have a pointer on hover).

### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

PR closed which adds more visual distinction (perhaps particularly on hover; ex. row background changes, add underline to text) and/or explanatory text.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Yeah, I agree that this behavior is really confusing right now
