### ISSUE TITLE
feature: replace `use_reranker` to `rerank_by` + add option to rerank by `crossencoder`, `semantic`,  `none`or `fulltext` for search routes

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1964]
### Description

We have popular demand for other rerranking strategies, for the sake of cleaness we should remove the option for `use_reranker` and replace it with an enum for `rerank_by`. For now I think the best options for reranking are 

- `crossencoder`
- `semantic`
- `fulltext`
- `none` (Not available if Hybrid search is activated)

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Finished in #1975
