### ISSUE TITLE
ops: figure out grpc with loadbalancer

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1970]
### Description

We are trying to ship out GRPC for the embedding server, the http clusterIP Service definition doesn't seem to be sufficient right now.

### Target(s)

`helm`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
I think this is a safe punt. Too low priority to really focus on right now.
