### ISSUE TITLE
bugfix: rather than redirecting to chunk page after creating on search playground, show banner

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1983]
### Description

Right now when users create chunks on the search playground, they get redirected to the page with that chunk. However since we do ingestion async, sometimes the chunk isn't processed in time making it feel broken. We should instead put a banner up after the user uploads a chunk that says that the chunk will be indexed soon and available for search.

### Target(s)

`search`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Done in #1990
