### ISSUE TITLE
cleanup: change DELETE routes so that they do not have request bodies

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#1989]
### Description

According to REST practices, DELETE operations should not have request bodies. modify these two routes so that they no longer have request bodies and instead provide all of the needed info in the url. Then update the clients to reflect the changes.

![image](https://github.com/user-attachments/assets/72bfbdfd-6781-4e6a-8873-a1413b2c15bd)

### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
This is delicate

**Comment by skeptrunedev** [comment]
I am certain that some API consumers are using this route w/ a request payload. Need to make sure we simply modify to support URL params and then use the body ones if they are not relevant. For the sake of the docs it should seem like there are no body params, but functionally they must remain.
