### ISSUE TITLE
bug: dashboard > dataset > URLs for the tabs have undefined in place of datasetId

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve#2011]
### Description

The dataset ID fails to render on the links:
- Start https://dashboard.trieve.ai/dashboard/dataset/undefined/start
- Events https://dashboard.trieve.ai/dashboard/dataset/undefined/events
- API Keys https://dashboard.trieve.ai/dashboard/dataset/undefined/api-keys
- Settings https://dashboard.trieve.ai/dashboard/dataset/undefined/settings

File: `frontends/dashboard/src/components/DatasetTabs.tsx`
Undefined: `urlParams.id`

Should probably be something more like this, from `trieve/frontends/dashboard/src/contexts/DatasetContext.tsx`
```
if (userContext?.user?.()) {
      const id = useParams().dataset_id;
      if (!id) return;
```

### Target(s)

frontends, dashboard

### Requirement to close

PR which ensures dataset is defined in the DatasetTabs.tsx

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Got this fixed in #2020
