### ISSUE TITLE
cleanup: use non-prefix expanded index for quote and negated word filters 

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#2031]
### Description

Since switching to the prefix expanded index for autocomplete, the experience for quote and negated words has been off. It needs to use a non prefix expanded index with Qdrant. 

### Target(s)

`server`

### Requirement to close

PR to use a non prefix expanded index for quote negated word filters 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by densumesh** [comment]
Can't create multiple indexes on one field

**Comment by skeptrunedev** [comment]
Not currently possible to solve this with Qdrant
