### ISSUE TITLE
feature: add a "Max Output Tokens" field in the Dataset Settings

### ISSUE THREAD

**Issue by jooni22** [devflowinc/trieve#2089]
### Description

Currently, the dataset settings lack an option to set the maximum number of output tokens for LLM responses. This feature would provide more control over response length and resource usage.
Proposed implementation:

- Add a "Max Output Tokens" field in the LLM Settings section
- If the field is empty or set to 0, use the default value or omit the parameter in the LLM API call
- If a value greater than 0 is set, include it in the LLM API request to limit the maximum number of output tokens

This addition would allow users to:

Control response length for specific use cases
Manage API usage and costs more effectively
Optimize performance for applications with strict response time requirements

The setting could be implemented similarly to existing parameters like Temperature and Presence Penalty, providing a consistent user experience.

### Target(s)

server/chat

**Comment by densumesh** [comment]
Fixed by #2124
