### ISSUE TITLE
feature: add typo tolerance to search 

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#2090]
### Description

Typo tolerance is a must have for search. We need to implement in a standard way. 

- [x] research approach to typo tolerance
- [x] implement typo tolerance with request payload flag that defaults to false on the search request 

### Target(s)

`server`

### Requirement to close

PR gets merged which adds typo tolerance 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by aaryanpunia** [comment]
The starting here would be a worker that backfills a pg table containing dataset <-> word mappings. This can then be used to construct a dictionary of words to spell check from.

**Comment by vtempest** [comment]
https://github.com/vtempest/ai-research-agent/blob/master/data/misspelled-typos-8k.json

I've been working on this issue for 3 wks and compiled this list of typos from 3 well updated sources into one that's 8k total pairs. 
I've been messaging you about integrating how you'd like
Instead you ignore and ban and block me on LinkedIn. Seems very anti open source leadership. There is nothing more repugnant and anti American than duscrimating against someone contributing for some rumors or personal petty issues you will see over the next 20 years
