### ISSUE TITLE
feature: update upload buttons to 'upload files'

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2098]
### Description

Trieve is excellent for searching large datasets. Let's nudge folks to upload sets of files by changing our language here. Change all buttons that currently say "upload file" to **upload files**

![Screenshot 2024-08-02 at 12 14 19 PM](https://github.com/user-attachments/assets/9baa8d05-8a08-4d3a-9230-3766db578eca)

### Target(s)

'dashboard'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by cdxker** [comment]
Was completed in #2105
