### ISSUE TITLE
enhancement: delete this sentence in the org creation modal + new copy

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2101]
### Description

We fixed this issue and now you can have multiple orgs with the same name. 

![Screenshot 2024-08-02 at 12 26 12 PM](https://github.com/user-attachments/assets/22f22656-2ace-4ae6-a460-b3717f2315b8)

While you're here, make the new copy read: 

You will be the owner of this organization.

Owners can invite others to join, create datasets within this organization, and manage its settings.

### Target(s)

'dashboard'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by vid277** [comment]
![image](https://github.com/user-attachments/assets/90630c75-f1dc-4f05-b387-200cd63d5c66)
