### ISSUE TITLE
bugfix: unwrap() on topic route which causes panic

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#2116]
### Description

There's an `unwrap` in the topic route which is causing a panic occasionally. 

### Target(s)

`server`

### Requirement to close

PR which identifies and removes all the `unwrap`'s in the topic route

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by densumesh** [comment]
Could not find unwrap
