### ISSUE TITLE
RAG Playground does not show a warning that no dataset is present

### ISSUE THREAD

**Issue by pmig** [devflowinc/trieve#2179]
### Description

As a user trying out the RAG Playground without a dataset the RAG Playground seems to be non responsive

### Target(s)

chat

### Requirement to close

Add a warning / link when accessing chat without a dataset, that a dataset is needed to chat with.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by cdxker** [comment]
Adding onto this, we also should display the same warning on Search, Chat and Analytics playgrounds

**Comment by drew-harris** [comment]
Analytics already has this warning, ill work on copying it over

**Comment by skeptrunedev** [comment]
Resolved in #2309
