### ISSUE TITLE
feature: switch to uuid payload indexes and map indexes

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2184]
### Description

Qdrant 1.11 brings support for uuid indexes with the is_tenannt = true flag. as well as indexes for hashmaps.
Will need to test if the hashmap index allows for many nested objects.

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by cdxker** [comment]
This is still on hold, as we have no yet migrated to qdrant 1.11 due to fear of instability

**Comment by skeptrunedev** [comment]
Not planned in the near-term future
