### ISSUE TITLE
feature: use universal group query api. (new feature in qdrant 1.11)

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2185]
### Description

Support for sort_by, rerank query and different rerank methods for groups similar to how we do for chunks. (New feature from qdrant 1.11). Will need a qdrant client version bump.

https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/query_points_groups

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Just not a priority right now
