### ISSUE TITLE
bugfix: file upload unable to chunk

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2230]
### Description

uploaded this file to Trieve cloud, didn't chunk. Pls fix. 

[AWS Marketplace Seller Guide.pdf](https://github.com/user-attachments/files/16698676/AWS.Marketplace.Seller.Guide.pdf)

### Target(s)

'ingestion'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by cdxker** [comment]
I think what is happening is that the file worker checks how many chunks the file is and errors if it exceeds the plan limit. Instead of adding only 1000 chunks, it errors and ads 0 chunks.

**Comment by cdxker** [comment]
Closing this issue redirecting it to #2232
