### ISSUE TITLE
bugfix: remove footnotes for now

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2231]
### Description

These footnotes on RAG are not cooperating, let's change the prompt so it doesn't attempt it
![Screenshot 2024-08-21 at 2 12 28 PM](https://github.com/user-attachments/assets/1bca7a8b-ba3e-4fd7-accd-52f384c7dbb6)

### Target(s)

'chat'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by fedhacks** [comment]
pinging this prompt whisperer @skeptrunedev

**Comment by skeptrunedev** [comment]
Has been completed
