### ISSUE TITLE
bug: Deleting all organizations on qdrant dashboard makes the server constantly make calls to `/auth/me` without resolving

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2239]
### Description

Delete all organizations in the trieve-dashboard. The front end gets stuck in a loop that doesn't let the user interact with the dashboard including disabling the ability to create a new organization

### Target(s)

`dashboard`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
Looking into this one, had this happen when i was doing org naming pr so I think i know whats going on
