### ISSUE TITLE
enhancement: prompt user to name org upon sign up

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2243]
### Description

let's make it to where users name their org upon sign up

### Target(s)

'dashboard'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
https://github.com/devflowinc/trieve/pull/2254
