### ISSUE TITLE
feat: route to efficiently retrieve list of existing tags across chunk tag_sets in dataset

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve#2284]
### Description

Imagine a dynamic use case where the Trieve dataset is the only or primary store of the data and the user adds chunks to a dataset through a form. The developer may want to have a list of tags in the dataset or fetch tags with a given prefix in order to autosuggest tags or show the user the common tags. Ex. a web-clippings search system. Or to provide autocomplete for users filtering by tags.

Eventually this dataset tag_set may become a dataset itself. Ex. StackOverflow's question-flow:
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/a832f7d5-b11e-49e9-8755-d2e9934fd9b0">

This sort of data may also be useful to dataset managers looking to optimize the tag-based retrieval.

Additional examples:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/eba048a6-5a26-4158-bb28-c15c86ed7cda">

### Target(s)

server

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
We actually do have this route - https://api.trieve.ai/redoc#tag/Dataset/operation/get_all_tags

Just need to add it to Mintlify docs

**Comment by skeptrunedev** [comment]
Fixed! - https://docs.trieve.ai/api-reference/dataset/get-all-tags#get-all-tags
