### ISSUE TITLE
feature: create glasskube package for firecrawl

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2304]
### Description

From #2300 make firecrawl be an optional package dependency of trieve with a glasskube package of firecrawl

### Target(s)

`glasskube`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Firecrawl was deployed w/out glasskube already
