### ISSUE TITLE
feature: make sparse vectors their own qdrant collection

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2306]
### Description

Because of the multivector implementation in Qdrant. dense vectors even if empty still take up storage. This poses an issue for people that want to disable dense vectors as it is pretty wasteful on space.

- [ ] create a new collection for sparse_vectors_only and have logic to route to this table.
- [ ] enabling / disabling sparse should be on dataset creation now and not modifiable anymore

### Target(s)

`server` `frontend`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by densumesh** [comment]
This would mess up our semantic and fulltext reranking as they rely on the vectors being in the same collection

**Comment by skeptrunedev** [comment]
Closing. This is very complex and can be solved by self-host'ers in a simpler way with creating a fulltext only collection that is alias'ed to one of the distance+dim specific collections that are created by default
