### ISSUE TITLE
feature: purchase rate to analytics

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#2311]
### Description

Analytics routes for the rates of purchasing, searches that didn't result in a purchase, searches that did result in a purchase. 
### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Low prio and blocked by analytics UI updates
