### ISSUE TITLE
feature: get all events

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#2313]
### Description

Route that returns a paginated list of all events in CH 

### Target(s)

`analytics`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Closing for now since this is blocked by UI improvements
