### ISSUE TITLE
bugfix: RAG dropdown results in 500 

### ISSUE THREAD

**Issue by SaraVieira** [devflowinc/trieve#2316]
### Description

When in the analytics for rag if you try to change what you are sorting by the call will result in a 500

![Peek 2024-09-09 19-23](https://github.com/user-attachments/assets/512e754f-6dc7-48a3-9792-fc1e5fa661b9)

### Target(s)

analytics

### Requirement to close

Calls should work 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Closing for now since this should get solved in the big table view later
