### ISSUE TITLE
feat: add dataset, organization, or query to the page title in dashboard+ pages so it shows in the tabs list

### ISSUE THREAD

**Issue by danielsgriffin** [devflowinc/trieve#2322]
### Description
This is a screenshot of some of my open tabs. These titles could include some information about which organization, dataset, or playground activity they are holding.

<img width="472" alt="image" src="https://github.com/user-attachments/assets/b79af0cd-0ad5-4cd8-9eb5-5fdb524f06bb">

Here is a screenshot of tab-search:
<img width="322" alt="image" src="https://github.com/user-attachments/assets/9fc93f41-c55c-40f3-98f0-e0f23adcb880">

This could be: `Trieve Dashboard: danielsgriffin.com` OR `Search Playground | Trieve: [blue unicorns]` OR `Search Playground | Trieve: Create chunk`

### Target(s)

dashboard, search, chat

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Agreed we should do this, but it's not planned for now
