### ISSUE TITLE
bug: "NO LABEL" display on analytics date picker

### ISSUE THREAD

**Issue by drew-harris** [devflowinc/trieve#2325]
### Description

<replace w/ a helpful description of your issue, including steps to replicate when/if relevant>
<img width="158" alt="image" src="https://github.com/user-attachments/assets/27ebf9a2-5bef-405c-8a07-d8b9cef05427">

When creating the component I forgot to add the string formatting logic for date ranges that don't include today. 

### Target(s)

`analytics`

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Closing for now in an effort to reduce scope on analytics issues
