### ISSUE TITLE
Evaluate using Profile-Guided Optimization (PGO) for Trieve

### ISSUE THREAD

**Issue by zamazan4ik** [devflowinc/trieve#2336]
Hi!

Recently I did many Profile-Guided Optimization (PGO) benchmarks on multiple projects (including many databases) - the results are available [here](https://github.com/zamazan4ik/awesome-pgo). I think such optimization can be useful for Trieve too for both cloud and on-premise installations.

We need to evaluate PGO applicability to Trieve. It can be applied to some parts of the Trieve itself (its Rust part) or 3rd party products from Trieve: ClickHouse, PostgreSQL, Redis, MongoDB (PGO benches are already available for them). If it helps to achieve better performance - add a note to the documentation about that. In this case, users and maintainers will be aware of another optimization opportunity for Trieve. Also, PGO integration into the build scripts can help users and maintainers easily apply PGO to their workloads. Even distributed by Trieve binaries can be pre-optimized with PGO on a generic-enough sample workload (e.g. `rustc` already does it).

After PGO, I can suggest evaluating [LLVM BOLT](https://github.com/llvm/llvm-project/blob/main/bolt/README.md) as an additional optimization step.

For the Rust projects, I recommend starting with [cargo-pgo](https://github.com/Kobzol/cargo-pgo) - it makes easier PGO optimization in many cases.

Thank you.

P.S. It's not an actual issue - just an improvement idea. I created the issue since Discussions are disabled for the repository.

**Comment by skeptrunedev** [comment]
Going to close for now since this work isn't going to be planned on our roadmap for quite some time. For now, we are fairly happy with performance. 

In the future, we will likely re-open.
