### ISSUE TITLE
documentation: add docs for deploying Clickhouse with docker compose

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#2359]
### Description

Clickhouse steps are missing from docker compose guide and need to be added.

### Target(s)

`self-hosting`

### Requirement to close

PR that adds clickhouse steps to docker compose self hosting guide section.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by cdxker** [comment]
No docs update is needed, just needed to have  `docker-compse.yml` be updated. The cp .env.example .env command works fine
