### ISSUE TITLE
feature: add `Create Organization` button to bottom of Org Selector

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#2375]
### Description

![image](https://github.com/user-attachments/assets/e1d22b8e-84c2-402d-8650-80b9a20fe03f)

User should have the ability to create a new organization from the bottom of the org select box.

### Target(s)

`dashboard`

### Requirement to close

PR which adds a create new org button to the bottom of the select as shown in the image.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
![image](https://github.com/user-attachments/assets/79ed866f-12bc-4c4d-9c30-7d0d4eead4cc)
would require decent refactor away from using the selectbox component
we already have this on the top left. feels weird to have two org selectors in the navbar
@skeptrunedev what were you missing from the one in the top right? (I was planning on replacing the "Switch Org" link with a quick switcher.

**Comment by drew-harris** [comment]
Playing around with this now
