### ISSUE TITLE
bugfix: header on dashboard breaks mobile layout 

### ISSUE THREAD

**Issue by SaraVieira** [devflowinc/trieve#2399]
### Description

When accessing the dashboard on mobile the layout is broken because of the header 
![Screenshot_20240924-200733](https://github.com/user-attachments/assets/73c462ac-1094-48f5-8e5b-8f78a05c45d8)

### Target(s)

Dashboard

### Requirement to close

Fix header layout so that it works on mobile 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
Handling this in #2436

**Comment by SaraVieira** [comment]
closes by https://github.com/devflowinc/trieve/pull/2436
