### ISSUE TITLE
docs: update all dataset event types that are being actively used

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2445]
### Description

Was looking at these events and some are not being used any more. ex: `qdrant_upload_failed` is not an event type that we create anymore 

![image](https://github.com/user-attachments/assets/e26a5716-dd3d-4d6c-8b71-32f40d92648e)

### Target(s)

`openapi` / `server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
Working on dataset crawl events now, ill try to clean this up as I go

**Comment by drew-harris** [comment]
Didn't see that @densumesh did this yesterday. closing issue.
