### ISSUE TITLE
feature: better onboarding flow

### ISSUE THREAD

**Issue by densumesh** [devflowinc/trieve#2446]
### Description

When a new user lands on the website, they should NOT be presented with the main dashboard as it can be super overwhelming w/ all of the features

We should instead: 
- [ ] When a new user lands on the dashboard, they should be presented with a splash screen that welcomes them to trieve
- [ ] Then they click the next button and they are prompted to give their dataset a name
- [ ] then they are prompted with a upload file component or a input to enter in their site to scrape
- [ ] then they can watch as chunks are uploaded into the service w/ some progress bar
- [ ] then they are given access to the search component so that they can test queries + rag
- [ ] then they are redirected to the main dashboard

### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by densumesh** [comment]
The goal is to avoid users from bouncing as soon as the see the main dashboard bc they have no idea how to get started/ upload chunks

**Comment by cdxker** [comment]
Prio on this is getting shifted down to medium. We need to focus on an end product that attract more signups
