### ISSUE TITLE
feature(search-component): `defaultSearchMode` as a parameter

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2450]
### Description

Add option for a `defaultSearchMode` parameter that is either `chat` or `search`

### Target(s)

`searchComponent`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by SaraVieira** [comment]
closed by https://github.com/devflowinc/trieve/pull/2418
