### ISSUE TITLE
feature: initial query suggestions as a parameter

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2463]
### Description

Add `initialQuerySuggestions` as a parameter. On Refresh button click, load in suggestions from route.

![image](https://github.com/user-attachments/assets/c3d28f83-09c9-4376-ac09-958d4559b08d)
![image](https://github.com/user-attachments/assets/2113dee4-ff05-4002-aec9-77a13102a8f7)

### Target(s)

`docsearch`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Doesn't require work in the Trieve repo. Just needs the props to be set in the `signoz-web` side
