### ISSUE TITLE
bugfix: information hovers are not displaying properly

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2561]
### Description

These information boxes should be within the bounds of the browser window. They currently are not.

### Target(s)

'dashboard'

<img width="479" alt="Screenshot 2024-10-10 at 8 13 45 PM" src="https://github.com/user-attachments/assets/ccbf40e6-a534-45d8-ab78-865d518c88cf">

### Requirement to close

These information boxes should be within the bounds of the browser window.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
ive always wanted to fix these
