### ISSUE TITLE
feature: add all event types to the event log

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2566]
### Description

Displaying accurate events that exist on a dataset is pretty important, its been out of date for sometime now I think the best way we keep it up to date from here is to add a route to query clickhouse on all the available events that exist on a dataset

![image](https://github.com/user-attachments/assets/43cc23a9-45f3-4ba2-ad8a-cf4cc33227d0)

### Target(s)

`server`

### Requirement to close

- [ ] route to get all dataset events that a `dataset_id`  ( should query clickhouse )
- [ ] redoc spec of the route
- [ ] display all event types on the frontend and query for the specified dataset event.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by densumesh** [comment]
Rather than another route, the /events route to get the events should also return the types of events available in the response
