### ISSUE TITLE
docs: clarify when positive chunk ids / positive tracking ids are needed in the error message

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2567]
### Description

On the response to recommend routes, we should return "Positive chunk ids could not be found, must return at least 1 positive id for X strategy " instead of "Positive chunk ids could not be found"

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by bandhan-majumder** [comment]
Hi @cdxker. Can I work on this issue?

**Comment by cdxker** [comment]
Yes you can! I'll assign you to it now. Let me know if you need help setting up the local development environment or ping me on the discord.

**Comment by bandhan-majumder** [comment]
Thank you.

**Comment by bandhan-majumder** [comment]
Sorry for being so late and not being able to solve the issue. It anyone else wants to take the issue, please take it. I am unassigning myself. Thanks for the opportunity. In future I hope to solve issues in this repo.
