### ISSUE TITLE
"Payload Too Large" error when running "fulltext" search

### ISSUE THREAD

**Issue by yujonglee** [devflowinc/trieve#2621]
### Description

I sometime got this error, even if query is short single word.
```bash
{:error, %{"message" => "Failed making call to server Status(413, Response[status: 413, status_text: Payload Too Large, url: http://embedding-server-splade-query.default.svc.cluster.local/embed_sparse])"}}
```

### Target(s)

search

### Requirement to close

Should not get this error

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Do you have an example query where you got this issue to occur by any chance? It's pretty tough to replicate

**Comment by yujonglee** [comment]
I could not reproduce it at the moment. Will report details when I got this again.
