### ISSUE TITLE
feature: add "recency_bias" feature back to the search ranking logic

### ISSUE THREAD

**Issue by yujonglee** [devflowinc/trieve#2624]
### Description

`recency_bias` is mentioned here:
https://docs.trieve.ai/guides/searching-with-trieve#important-parameters

But it is not listed in any of search api reference. And also, above link is mentioning `timestamp` field, but the field name in API reference is `time_stamp`, so bit confusing.

### Requirement to close

Clarify docs

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Ah, we actually removed this since writing that doc page. 

Is this an important feature for your use-case?

**Comment by yujonglee** [comment]
@skeptrunedev I think this is quite handy when searching GitHub Issues/Discussions since it's clear that recent issues are more important. However, I'm not sure if there are other use cases beyond that.

Also, I am currently sending `recency_bias=0.5` in the `search` request, but it is passing the input validation.

**Comment by skeptrunedev** [comment]
> @skeptrunedev I think this is quite handy when searching GitHub Issues/Discussions since it's clear that recent issues are more important. However, I'm not sure if there are other use cases beyond that.
> 
> Also, I am currently sending `recency_bias=0.5` in the `search` request, but it is passing the input validation.

Yeah, extra parameters don't cause the serialization to fail. We thought that was better than disallowing extra keys. 

I am very game to add this feature back. Going to change the issue to describe that.
