### ISSUE TITLE
feature: add "sort_options" for "Search Over Groups" route

### ISSUE THREAD

**Issue by yujonglee** [devflowinc/trieve#2656]
### Description

"sort_options" is missing in "Search Over Groups"

### Target(s)

"docs"

### Requirement to close

Update docs

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Added this to our backlog. Will likely get this done Friday this week or early next.
