### ISSUE TITLE
bugfix: search on public preview pages is broken

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2705]
### Description

search on public preview pages is broken, chat works fine though - see: https://api.trieve.ai/public_page/e20cd07a-1062-463a-8cfa-0e29f1078bd0

### Target(s)

'search' 

### Requirement to close

make it to where search works
### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by cdxker** [comment]
The dataset specified above is using api V1. Going to make the component explicitly use V2.
