### ISSUE TITLE
feature: 'stop generating' button should grey-out when not usable

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2746]
### Description

The 'stop generating' button does not change at all. Once a response is generated, is it still generating? not sure.

![image](https://github.com/user-attachments/assets/ac7a58ce-c5d5-48f6-bc16-b1f2eafda881)

### Target(s)

'sitesearch-component', 'chat'

### Requirement to close

either gray the button out or switch to having stop and play icons corresponding to the state of the generation

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Got shipped!
