### ISSUE TITLE
feature: finish making demo UI for pdf2md functional

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#2758]
### Description

- [x] feature: add input for pdf with tagline "PDF to Markdown conversion using Vision LLMs like GPT-4o" and sub-heading "powered by Trieve" w/ the star us button
- [x] feature: display the specified PDF in a R/L split on the left 
- [x] feature: display the markdown for the pages of the doc on the right
- [x] feature: include a JSON toggle to view the result as JSON
- [x] feature: make the UI functional by adding JS to poll the backend and hydrate results into the markdown/JSON display

#### Step 1

When the input is unpopulated put something like what Omni has w/ a simple form input and some sample docs on the page.

![image](https://github.com/user-attachments/assets/f9f57b72-6cf3-465e-b041-e8c62c2fe328)

#### Step 2

Once the form is populated, display a side-by-side of the pdf doc and markdown. Include the toggle for json. 

![image](https://github.com/user-attachments/assets/90bbd776-8820-43f3-861b-7ca9db41d54e)

### Target(s)

`pdf2md`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by vtempest** [comment]
https://airesearch.js.org/functions/convertPDFToHTML.html

Much more optimized way of doing in javascript in one function 

https://developers.cloudflare.com/vectorize/
Your hn demo which costs 5k a month can be run on $5 a month with Cloudflare 10mil storage and vecrorizing.

Nick Khami is beyond insulting in blocking and ignoring key research contributors that have proven highly valuable over last 2 years and above. This will get far worse over 20y with ai agents as your coworkers deserve to know that you will look for a petty excuse to block them and not be supportive of other developers. There's nothing wrong with listing on resume contributing to github open source projects. It is beyond repugnant that you would block for this.

**Comment by skeptrunedev** [comment]
Completed across several PR's over the last few days
