### ISSUE TITLE
feature: scoped search and chat 

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2771]
### Description

a lot of our sales motion for this relies on chat (and to a lesser extent, search) being able to work on specific products, collections, etc.

For example, I want to chat with the entire Guitars > Electric > 6-String > Hollow and Semi-Hollowbody collection. Maybe from there I click on one product and now want to chat specifically about one model. I know you can do this with our API, but we have to _show_ people. 

### Target(s)

'public-page'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
When someone takes this issue, they need to evaluate how much the tag_set which can be included on the search component can be used to solve for the ask here.
