### ISSUE TITLE
feature: rearrange images to display horizontally and make the section collapsable

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2774]
### Description

It would be good to make the images display horizontally and add a button that makes the images section collapsable

![Screenshot 2024-11-18 at 5 55 32 PM](https://github.com/user-attachments/assets/8731c59d-ea03-456c-b0bd-98599d0d0eb6)

### Target(s)

'search-playground'

### Requirement to close

<please describe what is required to close this issue here>

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by Subash-Mohan** [comment]
@skeptrunedev Hey, I would like to work on this ticket. Can you please assign me if no one is working on this.
