### ISSUE TITLE
feature: scan tags for keywords for search

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2776]
### Description

If I search "shorts for men" on a collection, I don't get shorts for men. 

![image](https://github.com/user-attachments/assets/9c0b54b7-fe2b-4f59-a8e4-87be3fb102aa)

However, "men" and tags of this sort are part of the JSON for the product.

![Screenshot 2024-11-18 at 6 20 00 PM](https://github.com/user-attachments/assets/3f0e0ce3-8a2e-415c-b79a-12265e0e7eae)

Let's figure out a way to manage these and make these types of queries work.

### Target(s)

'search', 'search-playground', 'public-page'

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by cdxker** [comment]
Looks like we are going to need some sort of boosting based on tags in this case. I think we can use tag_weights for this.

**Comment by skeptrunedev** [comment]
Solved in #2819
