### ISSUE TITLE
feature: collapse citations in RAG playground

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2794]
### Description

I know that the user can hover and resize each section, but this is hard to do. 

<img width="596" alt="Screenshot 2024-11-19 at 11 50 12 AM" src="https://github.com/user-attachments/assets/59d10a92-db4c-4efd-aad6-b91a097eff1b">

Add a button so the user can toggle the docs retrieved section
### Target(s)

'rag-playground'
### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Going to close for right now. May re-open in the future when this is something we have more time to do.
