### ISSUE TITLE
feature: show chunk count per group and fix pagination on groups view

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2821]
### Description

The user should know how many chunks are within a group. This is also super helpful for us in debugging.

![Screenshot 2024-11-20 at 4 07 24 PM](https://github.com/user-attachments/assets/cb24d60c-ca87-45ff-b427-45102bf482b3)

### Target(s)

`dashboard`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
thought this would be a quick fix, its not, reassigning to everyone
