### ISSUE TITLE
feature: move 'back to dashboard button' down and display logo on public page preview

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2835]
### Description

move the 'return to dashboard button down' so user can see the logo they set for public page. to see the logo you have to open up another browser and paste the link in. 

![Screenshot 2024-11-22 at 10 33 40 AM](https://github.com/user-attachments/assets/673a1924-121b-4195-83d7-f4d18d9af64f)

### Target(s)

'public-page'

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
Tying this one in with https://github.com/devflowinc/trieve/issues/2793
