### ISSUE TITLE
feature: env flag to disable inserting into chunk_metadata table

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2836]
### Description

env flag to disable inserting anything into postgres on the insert route. Will have to look at the downstream implications later on how it should search.

To close we should be able to both:

 - [x] Insert into qdrant without reading from postgresql
 - [x] Search without reading from postgresql

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
Shipped over the weekend in https://github.com/devflowinc/trieve/pull/2837
