### ISSUE TITLE
enhancement: default to hex in background color selector and allow copypasting

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2874]
### Description

Default the color field to hex as that's what we're grabbing colors in and easiest to copypaste. Also, please let me copypaste into the field. 

![image](https://github.com/user-attachments/assets/d98e7432-520a-4538-86a9-6c690d7d6e42)

### Target(s)

'dashboard', 'public-page'

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by skeptrunedev** [comment]
I just made them hex inputs
