### ISSUE TITLE
feature: overhaul search component for PDF-heavy datasets

### ISSUE THREAD

**Issue by fedhacks** [devflowinc/trieve#2902]
### Description

Search component is excellent for ecommerce/websites. People don't need to see the chunks in situ most of the time. However, for users interacting with PDFs, seeing them so is important.

The first step is to create cards that contain the relevant chunk and text (highlighted). 

![image](https://github.com/user-attachments/assets/7691dc0d-05b7-4ad2-b702-e0249cb0cabb)

Instead of highlighting an entire bounding box, we should use the highlights coming out of Trieve for a ctrl + f style word highlight in each image.

![Screenshot 2024-12-05 at 2 31 51 PM](https://github.com/user-attachments/assets/6b3abad2-94b9-473c-8f3b-e21fc262a2b2)

Additionally, the modal should increase in height to display at least 4 chunks so that users can get a good sense of the result's relevance. 

We should create a new mode, maybe called 'pdf mode'. Wow!

### Target(s)

`doc-search`, `public page`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by cdxker** [comment]
Closing this and converting to #2922
