### ISSUE TITLE
feature: make the health route open

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#802]
### Description

The health route should be openly pingable and not require auth.

### Target(s)

`server`

### Requirement to close

PR with 1 commit titled `feature: make the health route open` that makes the health route openly pingable. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by elisa-arenas** [comment]
I would like to work on this issue!

**Comment by skeptrunedev** [comment]
> I would like to work on this issue!

Assigned! We're around on Matrix and Discord to help out.
