### ISSUE TITLE
ops: publish our fork of the openai_dive crate as its own crate or get our PR merged into openai_dive

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#816]
### Description

Github link in the cargo.toml to our fork of openai_dive is kind of painful. Would be good to do it the more correct way. 

### Target(s)

`server`

### Requirement to close

- either publish a crate w/ our fork of openai_dive or get our PR merged 
- PR w/ 1 commit with a message of `ops: publish our fork of the openai_dive crate as its own crate or get our PR merged into openai_dive` that removes the github link to openai_dive in the cargo.toml

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by fastfists** [comment]
Closing becuase of https://github.com/tjardoo/openai-client/pull/50
