### ISSUE TITLE
feature: ability to see how many of each embedding type is stored.

### ISSUE THREAD

**Issue by fastfists** [devflowinc/trieve#861]
### Description

For card counts we look at what dim is stored. For ex: 1024 - 100 cards, 768 - 80 cards, ...

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
This is just dataset size
