### ISSUE TITLE
feature: file-unique search 

### ISSUE THREAD

**Issue by skeptrunedev** [devflowinc/trieve#875]
### Description

Should have the ability to specify that you want search results on the file-level instead of chunk-level. This will be helpful for blogs or knowledge management systems where you only want to see one "file" at a time as a result. Should use Qdrant's [search-groups](https://qdrant.tech/documentation/concepts/search/#search-groups) functionality for this. 

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by fastfists** [comment]
This is just #766 but more limiting.

**Comment by skeptrunedev** [comment]
> This is just #766 but more limiting.

wait I assumed 766 was like searching over collection names? was it for collection-unique?
